### ISSUE TITLE
semaphore permissions: Trying to set 0o666 results in 0o664 instead

### ISSUE THREAD

**Issue by Para7etamol** [emmt/InterProcessCommunication.jl#8]
Hi everyone!

When trying this:

```
using Random

sem_name="test_"*randstring(100)
rm(Semaphore,sem_name)
Semaphore(sem_name, 1; volatile=false, perms=0o666)
```

The resulting semaphore in /dev/shm/ has  permissions 0o664 instead of 0o666

Using Julia 1.10.0 and Ubuntu 2204

Best regards
Oliver

**Comment by emmt** [comment]
The permissions settings  are  masked  against the process `umask`. What is the value of your `umask`? I have tried your example and the resulting permissions are `0o644` because my `umask` is `0o022`.

**Comment by Para7etamol** [comment]
Thanks for your quick response!

I understand that using  default permissions (via umask) is a good idea, but I explicly specify the permissions so I expect them to be that way.

But it's pointless to whine because as I now see the masking is happening in sem_open ... :-(

**Comment by emmt** [comment]
In d9d91b0991438aa30bf0f6d734e45b57c9a9b6dd, I have added the `umask` function. So that you can call it as:

```julia
old_msk = umask(0) # set umask, remembering old value
sem = Semaphore(sem_name, 1; volatile=false, perms=0o666) # open semaphore
umask(old_msk) # restore old umask value
```
This should create the semaphore file with correct permissions. For now I have update the doc. to mention that the `perms` settings are masked against the process `umask`.

Perhaps it is better if this is automatically done under the hood by `Semaphore`. What do you think?

Once we decide on this, I can make a new release.

**Comment by Para7etamol** [comment]
To satisfy both expectations (mine to get what I specified and on the other hand people expecting sem_open's behaviour) you could make Semaphore() do the umasking under the hood, but let open(Semaphore,...) stick to sem_open / POSIX.

**Comment by emmt** [comment]
Done in 22d3a48f03758b4158bccb4116452c0df3118a92. Thanks for the suggestion.

I will register a new version as soon as I can get the documentation built again...

**Comment by emmt** [comment]
Done.
